@echo off
echo Installing MySQL service...
"C:\Program Files\MySQL\MySQL Server 8.4\bin\mysqld.exe" --install MySQL --defaults-file="C:\Program Files\MySQL\MySQL Server 8.4\my.ini"
echo Starting MySQL...
net start MySQL
echo Setting root password...
"C:\Program Files\MySQL\MySQL Server 8.4\bin\mysql.exe" -u root --skip-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root'; FLUSH PRIVILEGES;"
echo DONE!
